{"cells":[{"cell_type":"markdown","metadata":{"id":"nhde1biSjajW"},"source":["# **Setup for TLCS**"]},{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":15759,"status":"ok","timestamp":1702232075518,"user":{"displayName":"Hongzhi Shi","userId":"17821014659066953709"},"user_tz":300},"id":"8zjb7bq_jrSp","outputId":"f4472918-d5ff-479c-9488-2f7d268ac4e7"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"markdown","metadata":{"id":"CZ0Ptg7fkXrY"},"source":["Installing **SUMO TraCI**"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1051,"status":"ok","timestamp":1702232077998,"user":{"displayName":"Hongzhi Shi","userId":"17821014659066953709"},"user_tz":300},"id":"rTwUwTB0zOa8"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","pwd: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-7-933109ff6db7\u003e\", line 2, in \u003ccell line: 2\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/ELEN_6885/project/Deep-QLearning-Agent-for-Traffic-Signal-Control/TLCS/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-7-933109ff6db7\u003e\", line 2, in \u003ccell line: 2\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/ELEN_6885/project/Deep-QLearning-Agent-for-Traffic-Signal-Control/TLCS/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-7-933109ff6db7\u003e\", line 2, in \u003ccell line: 2\u003e\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/ELEN_6885/project/Deep-QLearning-Agent-for-Traffic-Signal-Control/TLCS/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["!pwd\n","%cd /content/drive/MyDrive/ELEN_6885/project/Deep-QLearning-Agent-for-Traffic-Signal-Control/TLCS/\n","!ls"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":101086,"status":"ok","timestamp":1702232180198,"user":{"displayName":"Hongzhi Shi","userId":"17821014659066953709"},"user_tz":300},"id":"3Oqs5WNyVpco","outputId":"37b53f15-52a2-4f68-8daa-d09b94b2c3c0"},"outputs":[{"name":"stdout","output_type":"stream","text":["Repository: 'deb https://ppa.launchpadcontent.net/sumo/stable/ubuntu/ jammy main'\n","Description:\n","SUMO is a highly portable, microscopic traffic simulation package designed to handle large road networks. SUMO is open source, licensed under the EPLv2.\n","More info: https://launchpad.net/~sumo/+archive/ubuntu/stable\n","Adding repository.\n","Adding deb entry to /etc/apt/sources.list.d/sumo-ubuntu-stable-jammy.list\n","Adding disabled deb-src entry to /etc/apt/sources.list.d/sumo-ubuntu-stable-jammy.list\n","Adding key to /etc/apt/trusted.gpg.d/sumo-ubuntu-stable.gpg with fingerprint 4B339D18DD12CA62CA0E400F87637B2A34012D7A\n","Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]\n","Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]\n","Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]\n","Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease\n","Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]\n","Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [633 kB]\n","Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease\n","Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]\n","Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]\n","Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease\n","Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1,282 kB]\n","Get:12 https://ppa.launchpadcontent.net/sumo/stable/ubuntu jammy InRelease [17.5 kB]\n","Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,304 kB]\n","Hit:14 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease\n","Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [28.5 kB]\n","Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,036 kB]\n","Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1,512 kB]\n","Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,576 kB]\n","Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1,572 kB]\n","Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [32.6 kB]\n","Get:21 https://ppa.launchpadcontent.net/sumo/stable/ubuntu jammy/main amd64 Packages [904 B]\n","Fetched 9,356 kB in 2s (4,198 kB/s)\n","Reading package lists... Done\n","Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease\n","Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease\n","Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease\n","Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease\n","Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease\n","Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease\n","Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease\n","Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease\n","Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease\n","Hit:10 https://ppa.launchpadcontent.net/sumo/stable/ubuntu jammy InRelease\n","Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease\n","Reading package lists... Done\n","Reading package lists... Done\n","Building dependency tree... Done\n","Reading state information... Done\n","The following additional packages will be installed:\n","  binfmt-support fastjar jarwrapper javascript-common libfox-1.6-0 libglu1-mesa libjs-openlayers\n","  libspatialindex-c6 libspatialindex-dev libspatialindex6 python3-certifi python3-numpy\n","  python3-pyproj python3-rtree\n","Suggested packages:\n","  apache2 | lighttpd | httpd python-numpy-doc python3-pytest\n","The following NEW packages will be installed:\n","  binfmt-support fastjar jarwrapper javascript-common libfox-1.6-0 libglu1-mesa libjs-openlayers\n","  libspatialindex-c6 libspatialindex-dev libspatialindex6 python3-certifi python3-numpy\n","  python3-pyproj python3-rtree sumo sumo-doc sumo-tools\n","0 upgraded, 17 newly installed, 0 to remove and 29 not upgraded.\n","Need to get 122 MB of archives.\n","After this operation, 621 MB of additional disk space will be used.\n","Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 binfmt-support amd64 2.2.1-2 [55.8 kB]\n","Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fastjar amd64 2:0.98-7 [67.1 kB]\n","Get:3 https://ppa.launchpadcontent.net/sumo/stable/ubuntu jammy/main amd64 sumo amd64 1.19.0-1 [28.6 MB]\n","Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 jarwrapper all 0.78 [10.8 kB]\n","Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 javascript-common all 11+nmu1 [5,936 B]\n","Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglu1-mesa amd64 9.0.2-1 [145 kB]\n","Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libfox-1.6-0 amd64 1.6.57-1build1 [890 kB]\n","Get:8 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libspatialindex6 amd64 1.9.3-2 [247 kB]\n","Get:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libspatialindex-c6 amd64 1.9.3-2 [55.8 kB]\n","Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 python3-certifi all 2020.6.20-1 [150 kB]\n","Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-numpy amd64 1:1.21.5-1ubuntu22.04.1 [3,467 kB]\n","Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 python3-pyproj amd64 3.3.0-2build1 [317 kB]\n","Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libspatialindex-dev amd64 1.9.3-2 [16.0 kB]\n","Get:14 http://archive.ubuntu.com/ubuntu jammy/universe amd64 python3-rtree all 0.9.7-1 [46.4 kB]\n","Get:15 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libjs-openlayers all 2.13.1+ds2-8 [709 kB]\n","Get:16 https://ppa.launchpadcontent.net/sumo/stable/ubuntu jammy/main amd64 sumo-doc all 1.19.0-1 [62.1 MB]\n","Get:17 https://ppa.launchpadcontent.net/sumo/stable/ubuntu jammy/main amd64 sumo-tools all 1.19.0-1 [24.8 MB]\n","Fetched 122 MB in 5s (22.6 MB/s)\n","Selecting previously unselected package binfmt-support.\n","(Reading database ... 120899 files and directories currently installed.)\n","Preparing to unpack .../00-binfmt-support_2.2.1-2_amd64.deb ...\n","Unpacking binfmt-support (2.2.1-2) ...\n","Selecting previously unselected package fastjar.\n","Preparing to unpack .../01-fastjar_2%3a0.98-7_amd64.deb ...\n","Unpacking fastjar (2:0.98-7) ...\n","Selecting previously unselected package jarwrapper.\n","Preparing to unpack .../02-jarwrapper_0.78_all.deb ...\n","Unpacking jarwrapper (0.78) ...\n","Selecting previously unselected package javascript-common.\n","Preparing to unpack .../03-javascript-common_11+nmu1_all.deb ...\n","Unpacking javascript-common (11+nmu1) ...\n","Selecting previously unselected package libglu1-mesa:amd64.\n","Preparing to unpack .../04-libglu1-mesa_9.0.2-1_amd64.deb ...\n","Unpacking libglu1-mesa:amd64 (9.0.2-1) ...\n","Selecting previously unselected package libfox-1.6-0:amd64.\n","Preparing to unpack .../05-libfox-1.6-0_1.6.57-1build1_amd64.deb ...\n","Unpacking libfox-1.6-0:amd64 (1.6.57-1build1) ...\n","Selecting previously unselected package libspatialindex6:amd64.\n","Preparing to unpack .../06-libspatialindex6_1.9.3-2_amd64.deb ...\n","Unpacking libspatialindex6:amd64 (1.9.3-2) ...\n","Selecting previously unselected package libspatialindex-c6:amd64.\n","Preparing to unpack .../07-libspatialindex-c6_1.9.3-2_amd64.deb ...\n","Unpacking libspatialindex-c6:amd64 (1.9.3-2) ...\n","Selecting previously unselected package python3-certifi.\n","Preparing to unpack .../08-python3-certifi_2020.6.20-1_all.deb ...\n","Unpacking python3-certifi (2020.6.20-1) ...\n","Selecting previously unselected package python3-numpy.\n","Preparing to unpack .../09-python3-numpy_1%3a1.21.5-1ubuntu22.04.1_amd64.deb ...\n","Unpacking python3-numpy (1:1.21.5-1ubuntu22.04.1) ...\n","Selecting previously unselected package python3-pyproj.\n","Preparing to unpack .../10-python3-pyproj_3.3.0-2build1_amd64.deb ...\n","Unpacking python3-pyproj (3.3.0-2build1) ...\n","Selecting previously unselected package libspatialindex-dev:amd64.\n","Preparing to unpack .../11-libspatialindex-dev_1.9.3-2_amd64.deb ...\n","Unpacking libspatialindex-dev:amd64 (1.9.3-2) ...\n","Selecting previously unselected package python3-rtree.\n","Preparing to unpack .../12-python3-rtree_0.9.7-1_all.deb ...\n","Unpacking python3-rtree (0.9.7-1) ...\n","Selecting previously unselected package sumo.\n","Preparing to unpack .../13-sumo_1.19.0-1_amd64.deb ...\n","Unpacking sumo (1.19.0-1) ...\n","Selecting previously unselected package sumo-doc.\n","Preparing to unpack .../14-sumo-doc_1.19.0-1_all.deb ...\n","Unpacking sumo-doc (1.19.0-1) ...\n","Selecting previously unselected package libjs-openlayers.\n","Preparing to unpack .../15-libjs-openlayers_2.13.1+ds2-8_all.deb ...\n","Unpacking libjs-openlayers (2.13.1+ds2-8) ...\n","Selecting previously unselected package sumo-tools.\n","Preparing to unpack .../16-sumo-tools_1.19.0-1_all.deb ...\n","Unpacking sumo-tools (1.19.0-1) ...\n","Setting up fastjar (2:0.98-7) ...\n","Setting up javascript-common (11+nmu1) ...\n","Setting up libspatialindex6:amd64 (1.9.3-2) ...\n","Setting up sumo-doc (1.19.0-1) ...\n","Setting up python3-certifi (2020.6.20-1) ...\n","Setting up binfmt-support (2.2.1-2) ...\n","invoke-rc.d: could not determine current runlevel\n","invoke-rc.d: policy-rc.d denied execution of restart.\n","Created symlink /etc/systemd/system/multi-user.target.wants/binfmt-support.service → /lib/systemd/system/binfmt-support.service.\n","Setting up python3-numpy (1:1.21.5-1ubuntu22.04.1) ...\n","Setting up libjs-openlayers (2.13.1+ds2-8) ...\n","Setting up libglu1-mesa:amd64 (9.0.2-1) ...\n","Setting up libfox-1.6-0:amd64 (1.6.57-1build1) ...\n","Setting up sumo (1.19.0-1) ...\n","Setting up libspatialindex-c6:amd64 (1.9.3-2) ...\n","Setting up jarwrapper (0.78) ...\n","Setting up libspatialindex-dev:amd64 (1.9.3-2) ...\n","Setting up python3-pyproj (3.3.0-2build1) ...\n","Setting up python3-rtree (0.9.7-1) ...\n","Setting up sumo-tools (1.19.0-1) ...\n","Processing triggers for man-db (2.10.2-1) ...\n","Processing triggers for libc-bin (2.35-0ubuntu3.4) ...\n","/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link\n","\n","/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link\n","\n","/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link\n","\n","/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link\n","\n","/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link\n","\n","/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link\n","\n","Collecting traci\n","  Downloading traci-1.19.0-py3-none-any.whl (124 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m124.5/124.5 kB\u001b[0m \u001b[31m1.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting keras-nlp\n","  Downloading keras_nlp-0.6.4-py3-none-any.whl (584 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m584.8/584.8 kB\u001b[0m \u001b[31m7.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting sumolib\u003e=1.19.0 (from traci)\n","  Downloading sumolib-1.19.0-py3-none-any.whl (148 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m148.8/148.8 kB\u001b[0m \u001b[31m13.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting keras-core (from keras-nlp)\n","  Downloading keras_core-0.1.7-py3-none-any.whl (950 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m950.8/950.8 kB\u001b[0m \u001b[31m21.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from keras-nlp) (1.4.0)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from keras-nlp) (1.23.5)\n","Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-nlp) (23.2)\n","Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from keras-nlp) (2023.6.3)\n","Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras-nlp) (13.7.0)\n","Requirement already satisfied: dm-tree in /usr/local/lib/python3.10/dist-packages (from keras-nlp) (0.1.8)\n","Collecting tensorflow-text (from keras-nlp)\n","  Downloading tensorflow_text-2.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.2/5.2 MB\u001b[0m \u001b[31m53.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting namex (from keras-core-\u003ekeras-nlp)\n","  Downloading namex-0.0.7-py3-none-any.whl (5.8 kB)\n","Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from keras-core-\u003ekeras-nlp) (3.9.0)\n","Requirement already satisfied: markdown-it-py\u003e=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich-\u003ekeras-nlp) (3.0.0)\n","Requirement already satisfied: pygments\u003c3.0.0,\u003e=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich-\u003ekeras-nlp) (2.16.1)\n","Requirement already satisfied: tensorflow-hub\u003e=0.13.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow-text-\u003ekeras-nlp) (0.15.0)\n","Collecting tensorflow\u003c2.16,\u003e=2.15.0 (from tensorflow-text-\u003ekeras-nlp)\n","  Downloading tensorflow-2.15.0.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (475.2 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m475.2/475.2 MB\u001b[0m \u001b[31m2.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py\u003e=2.2.0-\u003erich-\u003ekeras-nlp) (0.1.2)\n","Requirement already satisfied: astunparse\u003e=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (1.6.3)\n","Requirement already satisfied: flatbuffers\u003e=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (23.5.26)\n","Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,\u003e=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.4.0)\n","Requirement already satisfied: google-pasta\u003e=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.2.0)\n","Requirement already satisfied: libclang\u003e=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (16.0.6)\n","Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.2.0)\n","Requirement already satisfied: opt-einsum\u003e=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.3.0)\n","Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,\u003c5.0.0dev,\u003e=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.20.3)\n","Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (67.7.2)\n","Requirement already satisfied: six\u003e=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (1.16.0)\n","Requirement already satisfied: termcolor\u003e=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (2.3.0)\n","Requirement already satisfied: typing-extensions\u003e=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (4.5.0)\n","Requirement already satisfied: wrapt\u003c1.15,\u003e=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (1.14.1)\n","Requirement already satisfied: tensorflow-io-gcs-filesystem\u003e=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.34.0)\n","Requirement already satisfied: grpcio\u003c2.0,\u003e=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (1.59.3)\n","Collecting tensorboard\u003c2.16,\u003e=2.15 (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp)\n","  Downloading tensorboard-2.15.1-py3-none-any.whl (5.5 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.5/5.5 MB\u001b[0m \u001b[31m55.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting tensorflow-estimator\u003c2.16,\u003e=2.15.0 (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp)\n","  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m442.0/442.0 kB\u001b[0m \u001b[31m27.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting keras\u003c2.16,\u003e=2.15.0 (from tensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp)\n","  Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.7/1.7 MB\u001b[0m \u001b[31m54.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: wheel\u003c1.0,\u003e=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse\u003e=1.6.0-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.42.0)\n","Requirement already satisfied: google-auth\u003c3,\u003e=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (2.17.3)\n","Collecting google-auth-oauthlib\u003c2,\u003e=0.5 (from tensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp)\n","  Downloading google_auth_oauthlib-1.1.0-py2.py3-none-any.whl (19 kB)\n","Requirement already satisfied: markdown\u003e=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.5.1)\n","Requirement already satisfied: requests\u003c3,\u003e=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (2.31.0)\n","Requirement already satisfied: tensorboard-data-server\u003c0.8.0,\u003e=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.7.2)\n","Requirement already satisfied: werkzeug\u003e=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.0.1)\n","Requirement already satisfied: cachetools\u003c6.0,\u003e=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth\u003c3,\u003e=1.6.3-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (5.3.2)\n","Requirement already satisfied: pyasn1-modules\u003e=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth\u003c3,\u003e=1.6.3-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.3.0)\n","Requirement already satisfied: rsa\u003c5,\u003e=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth\u003c3,\u003e=1.6.3-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (4.9)\n","Requirement already satisfied: requests-oauthlib\u003e=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib\u003c2,\u003e=0.5-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (1.3.1)\n","Requirement already satisfied: charset-normalizer\u003c4,\u003e=2 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.21.0-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.3.2)\n","Requirement already satisfied: idna\u003c4,\u003e=2.5 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.21.0-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.6)\n","Requirement already satisfied: urllib3\u003c3,\u003e=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.21.0-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (2.0.7)\n","Requirement already satisfied: certifi\u003e=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.21.0-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (2023.11.17)\n","Requirement already satisfied: MarkupSafe\u003e=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug\u003e=1.0.1-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (2.1.3)\n","Requirement already satisfied: pyasn1\u003c0.6.0,\u003e=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules\u003e=0.2.1-\u003egoogle-auth\u003c3,\u003e=1.6.3-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (0.5.1)\n","Requirement already satisfied: oauthlib\u003e=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib\u003e=0.7.0-\u003egoogle-auth-oauthlib\u003c2,\u003e=0.5-\u003etensorboard\u003c2.16,\u003e=2.15-\u003etensorflow\u003c2.16,\u003e=2.15.0-\u003etensorflow-text-\u003ekeras-nlp) (3.2.2)\n","Installing collected packages: sumolib, namex, traci, tensorflow-estimator, keras, keras-core, google-auth-oauthlib, tensorboard, tensorflow, tensorflow-text, keras-nlp\n","  Attempting uninstall: tensorflow-estimator\n","    Found existing installation: tensorflow-estimator 2.12.0\n","    Uninstalling tensorflow-estimator-2.12.0:\n","      Successfully uninstalled tensorflow-estimator-2.12.0\n","  Attempting uninstall: keras\n","    Found existing installation: keras 2.12.0\n","    Uninstalling keras-2.12.0:\n","      Successfully uninstalled keras-2.12.0\n","  Attempting uninstall: google-auth-oauthlib\n","    Found existing installation: google-auth-oauthlib 0.4.6\n","    Uninstalling google-auth-oauthlib-0.4.6:\n","      Successfully uninstalled google-auth-oauthlib-0.4.6\n","  Attempting uninstall: tensorboard\n","    Found existing installation: tensorboard 2.12.0\n","    Uninstalling tensorboard-2.12.0:\n","      Successfully uninstalled tensorboard-2.12.0\n","  Attempting uninstall: tensorflow\n","    Found existing installation: tensorflow 2.12.0\n","    Uninstalling tensorflow-2.12.0:\n","      Successfully uninstalled tensorflow-2.12.0\n","Successfully installed google-auth-oauthlib-1.1.0 keras-2.15.0 keras-core-0.1.7 keras-nlp-0.6.4 namex-0.0.7 sumolib-1.19.0 tensorboard-2.15.1 tensorflow-2.15.0.post1 tensorflow-estimator-2.15.0 tensorflow-text-2.15.0 traci-1.19.0\n"]}],"source":["!add-apt-repository ppa:sumo/stable -y\n","!apt-get update -y\n","!apt-get install sumo sumo-tools sumo-doc\n","!pip install traci keras-nlp"]},{"cell_type":"code","execution_count":4,"metadata":{"executionInfo":{"elapsed":5,"status":"ok","timestamp":1702232180199,"user":{"displayName":"Hongzhi Shi","userId":"17821014659066953709"},"user_tz":300},"id":"s-6v3Jk1oxwE"},"outputs":[],"source":["import os\n","os.environ['SUMO_HOME'] = \"/usr/share/sumo/\""]},{"cell_type":"markdown","metadata":{"id":"ebzkYv4_klSV"},"source":["**Starting Training Process**"]},{"cell_type":"code","execution_count":12,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":167,"status":"ok","timestamp":1702246917851,"user":{"displayName":"Hongzhi Shi","userId":"17821014659066953709"},"user_tz":300},"id":"b2ACqSSajWoT","outputId":"0377c605-dae7-4cb9-99e4-767ce0a78ce7"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","python3: can't open file 'training_main.py': [Errno 107] Transport endpoint is not connected\n"]}],"source":["!python training_main.py"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"is_HW61b5ZDa"},"outputs":[],"source":["!python testing_main.py"]},{"cell_type":"markdown","metadata":{"id":"EoyQMaWXkyu1"},"source":["Check the */models/* directory for output files"]}],"metadata":{"accelerator":"TPU","anaconda-cloud":{},"colab":{"name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"}},"nbformat":4,"nbformat_minor":0}